name: Publish

on:
  schedule:
    # Build daily (just a random early UTC time, that isn't around the hour. GA schedule event can be delayed during periods of high loads of actions runs, which include the start of every hour. If load is sufficiently high, some jobs may be dropped.  Schedule running at a different time of the hour)
    # * is a special character in YAML so you have to quote this string
    # 4:06 UTC = 10pm CST
    - cron: '6 4 * * *'
  push:
  workflow_dispatch:
    inputs:
      skipTests:
        type: boolean
        required: false
        default: false
        description: Whether to skip e2e tests for this run
      target:
        type: choice
        required: false
        default: "pages"
        options:
          - "pages"
          - "worker"
        description: "To CF pages or new worker in progres"

# Cancel in progress if making multiple prs or pushes to a branch. 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps: 
      - name: Determine environment
        id: determine_env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/prod' ]]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref }} == 'refs/heads/qa' ]]; then
            echo "ENV=qa" >> $GITHUB_OUTPUT
          else
            echo "ENV=dev" >> $GITHUB_OUTPUT
          fi
      - name: Load env vars
        id: load_secrets
        uses: 1password/load-secrets-action@v4
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: "op://DevOps/cloudflare-worker-deploy-token/CF_ACCOUNT_ID"
          CLOUDFLARE_API_TOKEN: "op://DevOps/cloudflare-worker-deploy-token/CF_API_TOKEN"
          WORDPRESS_REST_MENU_ENDPOINT: "op://DevOps/biel-env-vars/${{ steps.determine_env.outputs.ENV }}/${{ steps.determine_env.outputs.ENV }}-rest-menu-endpoint"
          CMS_URL: "op://DevOps/biel-env-vars/${{ steps.determine_env.outputs.ENV }}/${{ steps.determine_env.outputs.ENV }}-cms-url"
          SITE_URL: "op://DevOps/biel-env-vars/${{ steps.determine_env.outputs.ENV }}/${{ steps.determine_env.outputs.ENV }}-site-url"
          WORDPRESS_GQL_URL: "op://DevOps/biel-env-vars/${{ steps.determine_env.outputs.ENV }}/${{ steps.determine_env.outputs.ENV }}-graphql-url"
          PUBLIC_DATA_API_URL: "op://DevOps/biel-env-vars/${{ steps.determine_env.outputs.ENV }}/${{ steps.determine_env.outputs.ENV }}-public-data-api-url"
          TURNSTILE_PUBLIC_KEY: "op://DevOps/biel-env-vars/common/turnstile-public-key"
          CF_DEV_VARS: "op://DevOps/biel-env-vars/common/cf-dev-vars"
      - name: set prod variables
        id: load_prod_secrets
        uses: 1password/load-secrets-action@v4
        if: github.ref == 'refs/heads/prod'
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CMS_URL: "op://DevOps/biel-env-vars/prod/prod-cms-url"
          SITE_URL: "op://DevOps/biel-env-vars/prod/prod-site-url"
          WORDPRESS_GQL_URL: "op://DevOps/biel-env-vars/prod/prod-graphql-url"

      - name: Checkout
        uses: actions/checkout@v4
      - name: get bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.10"
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      - name: Install JS dependencies and build
        run: |
          bun install --frozen-lockfile && bun run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          WORDPRESS_REST_MENU_ENDPOINT: ${{ steps.load_secrets.outputs.WORDPRESS_REST_MENU_ENDPOINT }}
          CMS_URL: ${{ github.ref == 'refs/heads/prod' && steps.load_prod_secrets.outputs.CMS_URL || steps.load_secrets.outputs.CMS_URL }}
          SITE_URL: ${{ github.ref == 'refs/heads/prod' && steps.load_prod_secrets.outputs.SITE_URL || steps.load_secrets.outputs.SITE_URL }}
          WORDPRESS_GQL_URL: ${{ github.ref == 'refs/heads/prod' && steps.load_prod_secrets.outputs.WORDPRESS_GQL_URL || steps.load_secrets.outputs.WORDPRESS_GQL_URL }}
          PUBLIC_DATA_API_URL: ${{ steps.load_secrets.outputs.PUBLIC_DATA_API_URL }}
          TURNSTILE_PUBLIC_KEY: ${{ steps.load_secrets.outputs.TURNSTILE_PUBLIC_KEY }}
          IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/prod' }}

      - name: Purge extra css
        run: |
          bun run purgecss
      - name: Generate Pagefind index
        run: |
          bun run pagefind
        env:
            CMS_URL:  ${{ github.ref == 'refs/heads/prod' && steps.load_prod_secrets.outputs.CMS_URL || steps.load_secrets.outputs.CMS_URL }}
            SITE_URL:  ${{ github.ref == 'refs/heads/prod' && steps.load_prod_secrets.outputs.SITE_URL || steps.load_secrets.outputs.SITE_URL }}
            WORDPRESS_GQL_URL:  ${{ github.ref == 'refs/heads/prod' && steps.load_prod_secrets.outputs.WORDPRESS_GQL_URL || steps.load_secrets.outputs.WORDPRESS_GQL_URL }}
            PUBLIC_DATA_API_URL: ${{ steps.load_secrets.outputs.PUBLIC_DATA_API_URL }}
      
      - name: Copy in cf dev vars if testing
        run: |
          printf "%s\n" "${{ steps.load_secrets.outputs.CF_DEV_VARS }}" > .dev.vars
        if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/prod'
      - name: Install Playwright Browsers
        run: bun playwright install --with-deps
        if: ${{inputs.skipTests != true}}
      - name: Run Playwright tests
        run: bun playwright test
        if: ${{inputs.skipTests != true}}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      - name: upload dist folder as artifact for debugging
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 21
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ steps.load_secrets.outputs.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ steps.load_secrets.outputs.CLOUDFLARE_ACCOUNT_ID }}
          command: ${{ inputs.target == 'worker' && 'deploy' || 'pages deploy dist --project-name=headless-biel --upload-source-maps=true' }}
